version: '3'
services:
 sut:
  build:
    context: .
    dockerfile: Dockerfile.test
  depends_on: 
    - dockerapp
 dockerapp:
  build: 
    context: .
    dockerfile: Dockerfile
  ports:
   - "4999:5000"
  depends_on:
   - redis
 redis:
   image: redis:3.2.0
